version: '3.4'

services:
  deploywithdatabaseupdate:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_HTTPS_PORT=44354
    ports:
      - "3097:80"
      - "44354:443"
    #volumes:
      #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      #- ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
