apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-your-project
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /data
    server: nfs-server-address
  persistentVolumeReclaimPolicy: Retain
